import { generatePDF } from "./dtr.js";
export const loadSelection = () => {
  var loadselection = $("#dtr_selection_employee").DataTable({
    paging: true,
    ordering: true,
    info: true,
    responsive: true,
    columnDef: [{ targets: 0, width: "50%" }],
    language: {
      search: "_INPUT_",
      searchPlaceholder: "Search table...",
    },
  });

  $("#select-all").on("click", function () {
    var isChecked = this.checked;

    // Select or deselect all checkboxes in the table
    $(".row-checkbox").prop("checked", isChecked);
  });

  // Handle click on individual row checkboxes
  $("#dtr_selection_employee tbody").on("change", ".row-checkbox", function () {
    // If any checkbox is not checked, uncheck "Select All"
    if (!this.checked) {
      $("#select-all").prop("checked", false);
    }

    // If all checkboxes are checked, check "Select All"
    if ($(".row-checkbox:checked").length === $(".row-checkbox").length) {
      $("#select-all").prop("checked", true);
    }
  });

  $("#submit-selected").on("click", async function () {
    // Collect names of selected users
    var selectedUsers = [];
    $(".row-checkbox:checked").each(function () {
      var userName = $(this).data("name"); // Get the data-name attribute
      selectedUsers.push(userName);
    });

    // Check if there are any selected users
    if (selectedUsers.length === 0) {
      alert("No users selected!");
      return;
    }

    // Send selected users to the server or process them
    console.log("Selected Users:", selectedUsers);

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "pt",
      format: [612, 792],
    });

    const datas = [
      {
        user: {
          idnumber: 3101,
          name: "Johnny Johnny ",
          department: "Human Resources",
          position: "HR Manager",
          employmentStatus: "Regular",
          location: "Head Office",
        },
        attendance: [
          [
            "01/01/2025",
            "Wed",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/02/2025",
            "Thu",
            "08:10",
            "18:05",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/03/2025",
            "Fri",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/04/2025",
            "Sat",
            "08:15",
            "18:10",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/05/2025",
            "Sun",
            "08:05",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/06/2025",
            "Mon",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/07/2025",
            "Tue",
            "08:20",
            "18:15",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/08/2025",
            "Wed",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/09/2025",
            "Thu",
            "08:05",
            "18:10",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/10/2025",
            "Fri",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/01/2025",
            "Wed",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/02/2025",
            "Thu",
            "08:10",
            "18:05",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/03/2025",
            "Fri",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/04/2025",
            "Sat",
            "08:15",
            "18:10",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/05/2025",
            "Sun",
            "08:05",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/06/2025",
            "Mon",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/07/2025",
            "Tue",
            "08:20",
            "18:15",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/08/2025",
            "Wed",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/09/2025",
            "Thu",
            "08:05",
            "18:10",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/10/2025",
            "Fri",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/01/2025",
            "Wed",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/02/2025",
            "Thu",
            "08:10",
            "18:05",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/03/2025",
            "Fri",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/04/2025",
            "Sat",
            "08:15",
            "18:10",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/05/2025",
            "Sun",
            "08:05",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/06/2025",
            "Mon",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/07/2025",
            "Tue",
            "08:20",
            "18:15",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/08/2025",
            "Wed",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/09/2025",
            "Thu",
            "08:05",
            "18:10",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/10/2025",
            "Fri",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
          [
            "01/10/2025",
            "Fri",
            "08:00",
            "18:00",
            "08:00",
            "17:00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        ],
      },
    ];

    for (let i = 0; i < datas.length; i++) {
      console.log("hehehe");

      const data = datas[i];
      const { user, attendance } = data;
      await generatePDF(doc, user, attendance);
      if (i < datas.length - 1) {
        doc.addPage();
      }
    }
    const height = window.innerHeight - 50;
    const pdfBlob = doc.output("blob");
    const pdfURL = URL.createObjectURL(pdfBlob);
    const iframe = document.createElement("iframe");
    iframe.src = pdfURL;
    iframe.style.width = "100%";
    iframe.style.height = height + "px";
    const previewContainer = document.getElementById("pdfPreview");
    previewContainer.innerHTML = "";
    previewContainer.appendChild(iframe);
  });
};
